# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: directory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'directory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64irectory.proto\x12\x0c\x64irectory.v1\"P\n\x0cNodeIdentity\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x15\n\ragent_version\x18\x02 \x01(\t\x12\x15\n\rwg_rs_version\x18\x03 \x01(\t\"\x8a\x02\n\x17NodeRegistrationRequest\x12,\n\x08identity\x18\x01 \x01(\x0b\x32\x1a.directory.v1.NodeIdentity\x12\x11\n\tregion_id\x18\x02 \x01(\t\x12\x16\n\x0einternal_wg_ip\x18\x03 \x01(\t\x12\x12\n\negress_ips\x18\x04 \x03(\t\x12M\n\x0c\x63\x61pabilities\x18\x05 \x03(\x0b\x32\x37.directory.v1.NodeRegistrationRequest.CapabilitiesEntry\x1a\x33\n\x11\x43\x61pabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x18NodeRegistrationResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"P\n\x10HeartbeatRequest\x12,\n\x08identity\x18\x01 \x01(\x0b\x32\x1a.directory.v1.NodeIdentity\x12\x0e\n\x06status\x18\x02 \x01(\t\"4\n\x11HeartbeatResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"D\n\x0c\x43onfigUpdate\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\twg_config\x18\x02 \x01(\x0c\x12\x10\n\x08revision\x18\x03 \x01(\x03\x32\x85\x02\n\x10\x44irectoryService\x12Y\n\x08Register\x12%.directory.v1.NodeRegistrationRequest\x1a&.directory.v1.NodeRegistrationResponse\x12L\n\tHeartbeat\x12\x1e.directory.v1.HeartbeatRequest\x1a\x1f.directory.v1.HeartbeatResponse\x12H\n\x0cStreamConfig\x12\x1a.directory.v1.NodeIdentity\x1a\x1a.directory.v1.ConfigUpdate0\x01\x42LZJgithub.com/example/vpn_mvp/services/common/protos/directory/v1;directoryv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'directory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/example/vpn_mvp/services/common/protos/directory/v1;directoryv1'
  _globals['_NODEREGISTRATIONREQUEST_CAPABILITIESENTRY']._loaded_options = None
  _globals['_NODEREGISTRATIONREQUEST_CAPABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_NODEIDENTITY']._serialized_start=33
  _globals['_NODEIDENTITY']._serialized_end=113
  _globals['_NODEREGISTRATIONREQUEST']._serialized_start=116
  _globals['_NODEREGISTRATIONREQUEST']._serialized_end=382
  _globals['_NODEREGISTRATIONREQUEST_CAPABILITIESENTRY']._serialized_start=331
  _globals['_NODEREGISTRATIONREQUEST_CAPABILITIESENTRY']._serialized_end=382
  _globals['_NODEREGISTRATIONRESPONSE']._serialized_start=384
  _globals['_NODEREGISTRATIONRESPONSE']._serialized_end=443
  _globals['_HEARTBEATREQUEST']._serialized_start=445
  _globals['_HEARTBEATREQUEST']._serialized_end=525
  _globals['_HEARTBEATRESPONSE']._serialized_start=527
  _globals['_HEARTBEATRESPONSE']._serialized_end=579
  _globals['_CONFIGUPDATE']._serialized_start=581
  _globals['_CONFIGUPDATE']._serialized_end=649
  _globals['_DIRECTORYSERVICE']._serialized_start=652
  _globals['_DIRECTORYSERVICE']._serialized_end=913
# @@protoc_insertion_point(module_scope)
