{
 "title": "OpenVPN Overview",
 "tags": [ "openvpn" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "openvpn_connected_clients" }
   ]
  },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(openvpn_server_bytes_in_total[2m])"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(openvpn_server_bytes_out_total[2m])"
    }
   ]
  }
 ]
}