server:
	verbosity: 0
	do-daemonize: no
	interface: 0.0.0.0
	interface: ::0
	port: 53
	harden-glue: yes
	hide-identity: yes
	hide-version: yes
	qname-minimisation: yes
	log-queries: no
	log-replies: no
	log-local-actions: no
	access-control: 0.0.0.0/0 allow
	access-control: ::0/0 allow

forward-zone:
	name: "."
	forward-tls-upstream: yes
	# Cloudflare DoT
	forward-addr: 1.1.1.1@853
	forward-addr: 1.0.0.1@853


