services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [mon]

  openvpn_exporter:
    image: kumina/openvpn-exporter
    command: ["--openvpn.status_paths=/status/status.log"]
    volumes:
      - ../server/openvpn/status:/status:ro
    ports:
      - "9176:9176"
    networks: [mon]

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=${POSTGRES_DSN}
    ports:
      - "9187:9187"
    networks: [mon]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks: [mon]

networks:
  mon:


