table inet vpn {
	chain prerouting {
		type filter hook prerouting priority 0;
	}
	chain forward {
		type filter hook forward priority 0;
		policy drop;
		iifname "wg0" accept
		oifname "wg0" accept
	}
	chain postrouting {
		type nat hook postrouting priority 100;
		oifname != "wg0" masquerade
	}
}


