[package]
name = "desktop-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
vpn_core = { package = "vpn-core", path = "../../../client/vpn-core" }
async-trait = "0.1"
base64 = "0.22"
tempfile = "3"

[target.'cfg(target_os = "windows")'.dependencies]
platform_windows = { package = "platform-windows", path = "../../../client/platform-windows" }

[target.'cfg(target_os = "macos")'.dependencies]
platform_macos = { package = "platform-macos", path = "../../../client/platform-macos" }

[target.'cfg(target_os = "linux")'.dependencies]
platform_linux = { package = "platform-linux", path = "../../../client/platform-linux" }


