[package]
name = "vpn-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
vpn-core = { path = "../vpn-core" }

[target.'cfg(target_os = "linux")'.dependencies.platform-linux]
path = "../platform-linux"

[target.'cfg(target_os = "windows")'.dependencies]
platform-windows = { path = "../platform-windows" }

[target.'cfg(target_os = "macos")'.dependencies]
platform-macos = { path = "../platform-macos" }


